name: Build Wheels

on:
  workflow_dispatch:  # 手动触发
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_wheels:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10'] # Python 版本

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip and install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build

      - name: Build wheel
        run: |
          python -m build --wheel --outdir wheelhouse

      - name: Upload wheels as artifact
        uses: actions/upload-artifact@v3
        with:
          name: python-wheels
          path: wheelhouse/*.whl
